# Generated by Django 5.0.3 on 2024-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название команды')),
                ('namecommand', models.CharField(max_length=200, verbose_name='Команда')),
                ('game', models.CharField(max_length=200, verbose_name='Игра')),
            ],
        ),
    ]
