# Generated by Django 5.0.3 on 2024-05-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
